/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eraser_route_service_OsrmJniUtil */

#ifndef _Included_com_eraser_route_service_OsrmJniUtil
#define _Included_com_eraser_route_service_OsrmJniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eraser_route_service_OsrmJniUtil
 * Method:    getOsrmRouteResponse
 * Signature: (DDDD)Lcom/eraser/route/service/dto/OsrmRouteDto;
 */
JNIEXPORT jobject JNICALL Java_com_eraser_route_service_OsrmJniUtil_getOsrmRouteResponse
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
