/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eraser_jniosrm_OsrmJNI */

#ifndef _Included_com_eraser_jniosrm_OsrmJNI
#define _Included_com_eraser_jniosrm_OsrmJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eraser_jniosrm_OsrmJNI
 * Method:    getOsrmRoute
 * Signature: (DDDD)I
 */
JNIEXPORT jint JNICALL Java_com_eraser_jniosrm_OsrmJNI_getOsrmRoute
  (JNIEnv *, jobject, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
